name: blogpub
author: 'Brain Mayo'
branding:
  color: white
  icon: 'book-open'
description: 'Create blog posts using Medium and Dev.to APIs. Upload automatically all images.'
inputs:
  articles_folder:
    description: 'Folder where articles are placed'
    required: false
    default: blog
  medium_token:
    description: 'Medium API Token'
    required: true
  medium_base_url:
    description: 'Medium base URL'
    required: false
    default: 'https://api.medium.com/v1'
  medium_user_id:
    description: 'Medium user Id'
    required: true
  devto_token:
    description: 'Dev.to API Token'
    required: false
outputs:
  medium_url:
    description: 'The Medium URL of the published article'

  devto_url:
    description: 'The Dev.to URL of the published article'
runs:
  using: 'node16'
  main: 'dist/blogpub.js'
   
